---
- name: Install Deluge
  apt:
    name: deluged
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Remove legacy init.d script
  file:
    path: /etc/init.d/deluged
    state: absent
  notify: Reload daemons

- name: Create {{ deluge_group }} group
  group:
    name: "{{ deluge_group }}"
    state: present

- name: Create {{ deluge_user }} user
  user:
    name: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    state: present
    system: true
    create_home: false

- name: Create deluge directories and set ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
  loop:
    - "{{ deluge_config_directory }}"
    - "{{ deluge_config_directory }}/config"
    - /var/log/deluged

- name: Configure Deluge service
  template:
    src: deluged.service.j2
    dest: /lib/systemd/system/deluged.service
  notify:
    - Reload daemons
    - Restart Deluge

- name: Flush handlers
  meta: flush_handlers

- name: Enable Deluge service
  systemd:
    name: deluged
    state: started
    enabled: true
...
